
services:
  db:
    image: postgres:15-alpine
    container_name: phishing_quiz_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Sistemas1.
      POSTGRES_DB: phishing_quiz
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: phishing_quiz_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@fixandplay.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata: